# $FreeBSD$
  
PORTNAME=       openzfs
PKGNAMESUFFIX=	-PYTHON

COMMENT=        Python Utilties for OpenZFS

MASTERDIR=      ${.CURDIR}/../../sysutils/openzfs

.include "${MASTERDIR}/Makefile"

OPTIONS_DEFAULT=PYTHON
