# $FreeBSD$
  
PORTNAME=       openzfs
PKGNAMESUFFIX=	-tests	

COMMENT=        Tests for OpenZFS

MASTERDIR=      ${.CURDIR}/../../sysutils/openzfs

.include "${MASTERDIR}/Makefile"


RUN_DEPENDS+=	zfs:sysutils/openzfs
OPTIONS_DEFAULT=TESTS
