# Created by: Nick Wolff <darkfiberiru@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-spice

COMMENT=	Remmina plugin to execute a command

BUILD_DEPENDS+=	spice-gtk>=0.37:deskutils/spicegtk \
	        spice-protocol>=0.12.15:devel/spice-protocol


MASTERDIR=	${.CURDIR}/../remmina-plugins

.include "${MASTERDIR}/Makefile"
