# Created by: Nick Wolff <darkfiberiru@gmail.com>
# $FreeBSD$

PKGNAMESUFFIX=	-www

COMMENT=	Remmina plugin to execute a command

LIB_DEPENDS=	libwebkit2gtk-4.0.so:www/webkit2gtk3

MASTERDIR=	${.CURDIR}/../remmina-plugins

.include "${MASTERDIR}/Makefile"
